/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DepositorCoin__factory } from "./DepositorCoin__factory";
export { ERC20__factory } from "./ERC20__factory";
export { Lock__factory } from "./Lock__factory";
export { Oracle__factory } from "./Oracle__factory";
export { StableCoin__factory } from "./StableCoin__factory";
export { WadLib__factory } from "./WadLib__factory";
